services:
  web:
    build: ./app/templates
    restart: always
    ports:
      - "80:80"
    depends_on:
      - python_app

  python_app:
    build: ./app
    restart: always
    ports:
      - "8000:8000"

volumes:
  web_data: